version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./${JENKINS_LOCAL_HOME}/jenkins_configuration:/var/jenkins_home
      - ${HOST_DOCKER_SOCK}:/var/run/docker.sock
    networks:
      - jenkins

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: nginx
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "8080:80"    # http
      - "8443:443"   # https
    volumes:
      - ${JENKINS_LOCAL_HOME}:/var/jenkins_home
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl
      - ${NGINX_LOGS}:/var/log/nginx

networks:
  jenkins:
    name: cicd-jenkins
    driver: bridge

  # agent:
  #   image: jenkins/ssh-agent:jdk11
  #   privileged: true
  #   user: root
  #   container_name: agent
  #   expose:
  #     - 22
  #   environment:
  #     - JENKINS_AGENT_SSH_PUBKEY=${SSH_KEY}
  #   networks:
  #     - jenkins

  # python_agent:
  #   image: jenkins/jnlp-agent-python:latest
  #   privileged: true
  #   user: root
  #   container_name: python_agent
  #   expose:
  #     - 22
  #   environment:
  #     - JENKINS_AGENT_SSH_PUBKEY=${SSH_KEY}