trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
 - name: python.version
   value: 3.9

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python3 -m venv .venv
    source .venv/bin/activate
  displatName: Set virtual env

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs