name: python-flusk-actions
run-name: ${{ github.actor }} replace tokens

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Save env to file
        env:
          VARS: ${{ toJSON(vars) }}
        run: echo "$VARS" > "variables.json"

      - name: Print path
        run: pwd && ls -la

      - name: Read file
        run: cat Virtualization/Docker/CI-CD-tools/Jenkins/docker-compose.yml

      - name: Read env
        run: cat variables.json

