name: replace-tokens
run-name: ${{ github.actor }} replace tokens

on: push
env:
  JENKINS_LOCAL_HOME: ./jenkins_compose
  JENKINS_UID: 1000
  JENKINS_GID: 1000
  HOST_DOCKER_SOCK: /var/run/docker.sock
# Nginx Settings
  NGINX_CONF: ./nginx.conf
  NGINX_SSL_CERTS: ./ssl
  NGINX_LOGS: ./logs/nginx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Save envs to file
        env:
          VARS: ${{ toJSON(vars) }}
          SECRETS: ${{ toJSON(secrets) }}
        run: |
          echo "$VARS" > "variables.json"
          echo "$SECRETS" >> "variables.json"
          env >> "variables.json"

      - name: Replace - Using env variables
        run: envsubst < Virtualization/Docker/CI-CD-tools/Jenkins/docker-compose.yml > docker-compose.yml

      - name: Read files
        run: |
          cat variables.json
          echo "**********************"
          echo "**********************"
          cat docker-compose.yml
